version: "3"
services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: cool-school-db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cool-school
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    depends_on:
      - mysql-db
    links:
      - mysql-db:db
    networks:
      - cool-school
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_TYPE=mysql
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=test
      - DB_NAME=cool-school-db
    depends_on:
      - mysql-db
    networks:
      - cool-school
    command: npm start serve
networks:
  cool-school: {}
volumes:
  db_data:
