version: "3"
services:
  project-db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: cool-school-db
    volumes:
      - db_data:/docker-entrypoint-initdb.d/
    networks:
      - cool-school
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    depends_on:
      - project-db
    links:
      - project-db:db
    networks:
      - cool-school
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_TYPE=mysql
      - DB_HOST=project-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=test
      - DB_NAME=cool-school-db
    depends_on:
      - project-db
    networks:
      - cool-school
    command: npm start serve
networks:
  cool-school: {}
volumes:
  db_data:
